### ISSUE TITLE
Another bug?

### ISSUE THREAD

**Issue by Binket** [flori-schwa/VarLightOld#25]
Minecraft 1.12.2 

varlight version 1.8.3

use varlight give Admin snow 15 

and;gif

![2](https://user-images.githubusercontent.com/49503376/74085383-6dcd6480-4ab3-11ea-9964-4e632674857e.gif)

**Comment by flori-schwa** [comment]
The wiki says Snow blocks do not melt at high light levels but the source code says otherwise:

`net.minecraft.server.v1_15_R1.BlockSnow#tick` Method:

```java
    public void tick(IBlockData iblockdata, WorldServer worldserver, BlockPosition blockposition, Random random) {
        if (worldserver.getBrightness(EnumSkyBlock.BLOCK, blockposition) > 11) {
            if (CraftEventFactory.callBlockFadeEvent(worldserver, blockposition, Blocks.AIR.getBlockData()).isCancelled()) {
                return;
            }

            c(iblockdata, worldserver, blockposition);
            worldserver.a(blockposition, false);
        }

    }
```

(I used the 1.15 code because it is more readable than the 1.12 code, but it still does the same in 1.12)

This code basically turns the snow block into air if it emits a light level stronger than 11. Normally Snow Blocks cannot emit light, so this code normally never runs. But using VarLight, Snow blocks can be turned into Light sources, if they emit a light level more than 11 they will break. This is not a VarLight Bug, but a Minecraft bug.

If you want, I can prevent this from happening, since the BlockFadeEvent is cancellable.

**Comment by Binket** [comment]
oh Thanks. I' think use varLight prevent this from happening     ):
