### ISSUE TITLE
stuttering in certain areas after using fill command.

### ISSUE THREAD

**Issue by aldumgames** [flori-schwa/VarLightOld#30]
In certain areas after filling there's a stuttering problem, it's very slight.

**Comment by flori-schwa** [comment]
What exactly do you mean with "stuttering"? Do you have Screenshots or video?

**Comment by aldumgames** [comment]
let me upload this video

**Comment by aldumgames** [comment]
https://www.youtube.com/watch?v=uxPdPpi5W4o

**Comment by aldumgames** [comment]
https://drive.google.com/file/d/1g8lnbMBqv6dP1rtYmxaBzwAZykNPdZ-9/view?usp=sharing

**Comment by flori-schwa** [comment]
This is just Client Side lag. This can be caused by a Custom light source receiving block updates. In that case, the plugin has to send the Custom Light to the client again. This is the most likely cause of the lag. Try to find a custom light source that received a lot of updates (like a lightsource near a redstone contraption with moving pistons)

**Comment by aldumgames** [comment]
Is there a way to reset the lights

**Comment by flori-schwa** [comment]
Yes, fill the area again but use Light level 0 as a parameter

**Comment by aldumgames** [comment]
Alright thanks.
